Repository Harumeonglog/Harumeonglog-Server, pull requests merged in 2025-04, with the labels that each got.

#14 ✨ [Feat] Spring Security 적용
  build.gradle
  src/main/java/com/example/harumeonglog/domain/common/auth/annotation/AuthenticatedMember.java
  src/main/java/com/example/harumeonglog/domain/common/auth/annotation/resolver/AuthenticatedMemberResolver.java
  src/main/java/com/example/harumeonglog/domain/common/auth/domain/CustomUserDetails.java
  src/main/java/com/example/harumeonglog/domain/common/auth/exception/AuthErrorCode.java
  src/main/java/com/example/harumeonglog/domain/common/auth/exception/AuthException.java
  src/main/java/com/example/harumeonglog/domain/common/auth/filter/AbstractTokenFilter.java
  src/main/java/com/example/harumeonglog/domain/common/auth/filter/AbstractTokenLogoutFilter.java
  src/main/java/com/example/harumeonglog/domain/common/auth/filter/JwtTokenFilter.java
  src/main/java/com/example/harumeonglog/domain/common/auth/filter/JwtTokenLogoutFilter.java
  src/main/java/com/example/harumeonglog/domain/common/auth/handler/JwtTokenLogoutHandler.java
  src/main/java/com/example/harumeonglog/domain/common/auth/service/CustomDetailService.java
  src/main/java/com/example/harumeonglog/domain/common/auth/util/JwtUtil.java
  src/main/java/com/example/harumeonglog/domain/common/auth/util/RedisUtil.java
  src/main/java/com/example/harumeonglog/domain/common/config/RedisConfig.java
  src/main/java/com/example/harumeonglog/domain/common/config/SecurityConfig.java
  src/main/java/com/example/harumeonglog/domain/common/config/WebConfig.java
  src/main/java/com/example/harumeonglog/domain/member/domain/Member.java
  src/main/java/com/example/harumeonglog/domain/member/entity/MemberEntity.java
  src/main/java/com/example/harumeonglog/domain/member/exception/MemberErrorCode.java
  src/main/java/com/example/harumeonglog/domain/member/exception/MemberException.java
  src/main/java/com/example/harumeonglog/domain/member/infrastructure/MemberRepositoryImpl.java
  src/main/java/com/example/harumeonglog/domain/member/service/port/MemberRepository.java
  src/test/java/com/example/harumeonglog/restDocs/controller/MemberControllerTest.java
  src/test/java/com/example/harumeonglog/restDocs/controller/PostControllerTest.java
  src/test/java/com/example/harumeonglog/restDocs/controller/WalkControllerTest.java
Labels: ✨feature

#16 🚀 [Chore] test jacoco setting
  .github/workflows/ci.yml
  build.gradle
  src/main/java/com/example/harumeonglog/domain/event/entity/EventEntity.java
  src/main/java/com/example/harumeonglog/domain/event/entity/enums/EventCategory.java
  src/main/java/com/example/harumeonglog/domain/member/entity/InvitationEntity.java
  src/main/java/com/example/harumeonglog/domain/member/entity/NoticeEntity.java
  src/main/java/com/example/harumeonglog/domain/member/entity/enums/NoticeType.java
  src/main/java/com/example/harumeonglog/domain/member/entity/enums/SocialType.java
  src/main/java/com/example/harumeonglog/domain/pet/entity/MemberPetEntity.java
  src/main/java/com/example/harumeonglog/domain/pet/entity/PetEntity.java
  src/main/java/com/example/harumeonglog/domain/pet/entity/enums/Gender.java
  src/main/java/com/example/harumeonglog/domain/pet/entity/enums/MemberPetRole.java
  src/main/java/com/example/harumeonglog/domain/pet/entity/enums/PetSize.java
  src/main/java/com/example/harumeonglog/domain/post/controller/dto/enums/PostCategory.java
  src/main/java/com/example/harumeonglog/domain/post/controller/dto/request/PostRequest.java
  src/main/java/com/example/harumeonglog/domain/post/entity/PostEntity.java
  src/main/java/com/example/harumeonglog/domain/post/entity/enums/PostCategory.java
  src/test/java/com/example/harumeonglog/restDocs/controller/PostControllerTest.java
Labels: 🚀chore

#18 :rocket: [Chore] filter test 제외
  build.gradle
Labels: 🚀chore

#20 🧪 [Test] 초반 테스트 커버리지 용 post, comment test 추가
  src/main/java/com/example/harumeonglog/domain/comment/controller/port/CommentService.java
  src/main/java/com/example/harumeonglog/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/post/controller/PostController.java
  src/main/java/com/example/harumeonglog/domain/post/controller/port/PostCommandService.java
  src/main/java/com/example/harumeonglog/domain/post/controller/port/PostQueryService.java
  src/main/java/com/example/harumeonglog/domain/post/service/PostCommandServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/post/service/PostQueryServiceImpl.java
  src/test/java/com/example/harumeonglog/domain/comment/service/CommentServiceImplTest.java
  src/test/java/com/example/harumeonglog/domain/post/service/PostCommandServiceImplTest.java
  src/test/java/com/example/harumeonglog/domain/post/service/PostQueryServiceImplTest.java
  src/test/java/com/example/harumeonglog/restDocs/controller/PostControllerTest.java
Labels: :test_tube: test

#22 ✨ [Feat] EntryPoint, AccessDeniedHandler 적용 및 API 명세서 폼로그인 적용
  src/main/java/com/example/harumeonglog/domain/common/auth/exception/AuthErrorCode.java
  src/main/java/com/example/harumeonglog/domain/common/auth/handler/CustomAccessDeniedHandler.java
  src/main/java/com/example/harumeonglog/domain/common/auth/handler/CustomAuthorizationEntryPoint.java
  src/main/java/com/example/harumeonglog/domain/common/config/SecurityConfig.java
  src/main/java/com/example/harumeonglog/domain/common/controller/response/util/HttpResponseUtil.java
Labels: ✨feature

#27 :memo: [Docs] README.md 설명 추가
  README.md
Labels: :memo: docs

#28 🧪 [Test] Member, Walk에 대한 초반 테스트 커버리지용 테스트 추가
  src/main/java/com/example/harumeonglog/domain/common/auth/handler/JwtTokenLogoutHandler.java
  src/main/java/com/example/harumeonglog/domain/member/controller/dto/request/MemberRequest.java
  src/main/java/com/example/harumeonglog/domain/member/service/MemberServiceImpl.java
  src/test/java/com/example/harumeonglog/domain/common/auth/domain/CustomUserDetailsTest.java
  src/test/java/com/example/harumeonglog/domain/common/auth/handler/CustomAccessDeniedHandlerTest.java
  src/test/java/com/example/harumeonglog/domain/common/auth/handler/CustomAuthorizationEntryPointTest.java
  src/test/java/com/example/harumeonglog/domain/common/auth/handler/JwtTokenLogoutHandlerTest.java
  src/test/java/com/example/harumeonglog/domain/common/auth/service/CustomDetailServiceTest.java
  src/test/java/com/example/harumeonglog/domain/common/auth/util/JwtUtilTest.java
  src/test/java/com/example/harumeonglog/domain/member/service/MemberServiceImplTest.java
  src/test/java/com/example/harumeonglog/domain/mock/FakeJwtUtil.java
  src/test/java/com/example/harumeonglog/domain/mock/FakeMemberRepository.java
  src/test/java/com/example/harumeonglog/domain/walk/service/MemberWalkServiceImplTest.java
  src/test/java/com/example/harumeonglog/domain/walk/service/WalkServiceImplTest.java
Labels: :test_tube: test

#30 🧪 [Test] notice service, health checking test 추가
  src/docs/asciidoc/healthCheck.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/example/harumeonglog/domain/common/config/SecurityConfig.java
  src/main/java/com/example/harumeonglog/domain/common/controller/HealthCheckController.java
  src/main/java/com/example/harumeonglog/domain/member/service/NoticeServiceImpl.java
  src/test/java/com/example/harumeonglog/domain/member/service/NoticeServiceImplTest.java
  src/test/java/com/example/harumeonglog/restDocs/controller/HealthCheckContollerTest.java
  src/test/java/com/example/harumeonglog/restDocs/controller/HealthCheckControllerTest.java
Labels: ♻️refactor, :test_tube: test

#25 🧪 [Test] 초반 테스트 커버리지 용 event, pet test 추가 및 event 조인 전략 변경
  src/docs/asciidoc/event.adoc
  src/main/java/com/example/harumeonglog/domain/event/controller/EventController.java
  src/main/java/com/example/harumeonglog/domain/event/controller/dto/request/EventRequest.java
  src/main/java/com/example/harumeonglog/domain/event/controller/dto/response/EventResponse.java
  src/main/java/com/example/harumeonglog/domain/event/controller/port/EventService.java
  src/main/java/com/example/harumeonglog/domain/event/domain/BathEvent.java
  src/main/java/com/example/harumeonglog/domain/event/domain/Event.java
  src/main/java/com/example/harumeonglog/domain/event/domain/GeneralEvent.java
  src/main/java/com/example/harumeonglog/domain/event/domain/HospitalEvent.java
  src/main/java/com/example/harumeonglog/domain/event/domain/MedicineEvent.java
  src/main/java/com/example/harumeonglog/domain/event/domain/WalkEvent.java
  src/main/java/com/example/harumeonglog/domain/event/domain/enums/EventCategory.java
  src/main/java/com/example/harumeonglog/domain/event/entity/BathEventEntity.java
  src/main/java/com/example/harumeonglog/domain/event/entity/EventEntity.java
  src/main/java/com/example/harumeonglog/domain/event/entity/GeneralEventEntity.java
  src/main/java/com/example/harumeonglog/domain/event/entity/HospitalEventEntity.java
  src/main/java/com/example/harumeonglog/domain/event/entity/MedicineEventEntity.java
  src/main/java/com/example/harumeonglog/domain/event/entity/WalkEventEntity.java
  src/main/java/com/example/harumeonglog/domain/event/service/EventServiceImpl.java
  src/test/java/com/example/harumeonglog/domain/event/service/EventServiceImplTest.java
  src/test/java/com/example/harumeonglog/domain/pet/service/PetImageServiceImplTest.java
  src/test/java/com/example/harumeonglog/domain/pet/service/PetServiceImplTest.java
  src/test/java/com/example/harumeonglog/restDocs/controller/EventControllerTest.java
Labels: ♻️refactor, :test_tube: test

#32 :rocket: [Chore] jacoco test 클래스 수정
  build.gradle
Labels: 🚀chore

#34 :rocket: chore: Jacoco gradle 수정 및 ci 추가
  .github/workflows/ci.yml
  build.gradle
Labels: 🚀chore

#38 🚀 [Chore] cd 설정 추가
  .ebextensions/00-makeFiles.config
  .ebextensions/01-set-timezone.config
  .github/workflows/cd.yml
  .gitignore
  .platform/nginx.conf
  Procfile
  build.gradle
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: 🚀chore

#40 🐛 fix: cd 설정 수정
  .github/workflows/cd.yml
Labels: 🐛bug
