Repository Harumeonglog/Harumeonglog-Server, pull requests merged in 2025-03, with the labels that each got.

#2 ✨ [Feat] 산책 API RestDocs 작성
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/walk.adoc
  src/main/java/com/example/harumeonglog/domain/member/controller/dto/response/MemberResponse.java
  src/main/java/com/example/harumeonglog/domain/member/domain/Member.java
  src/main/java/com/example/harumeonglog/domain/pet/domain/Pet.java
  src/main/java/com/example/harumeonglog/domain/walk/controller/WalkController.java
  src/main/java/com/example/harumeonglog/domain/walk/controller/dto/request/MemberWalkRequest.java
  src/main/java/com/example/harumeonglog/domain/walk/controller/dto/request/WalkRequest.java
  src/main/java/com/example/harumeonglog/domain/walk/controller/dto/response/MemberWalkResponse.java
  src/main/java/com/example/harumeonglog/domain/walk/controller/dto/response/WalkPetResponse.java
  src/main/java/com/example/harumeonglog/domain/walk/controller/dto/response/WalkResponse.java
  src/main/java/com/example/harumeonglog/domain/walk/controller/port/MemberWalkService.java
  src/main/java/com/example/harumeonglog/domain/walk/controller/port/WalkService.java
  src/main/java/com/example/harumeonglog/domain/walk/domain/Walk.java
  src/main/java/com/example/harumeonglog/domain/walk/entity/WalkEntity.java
  src/main/java/com/example/harumeonglog/domain/walk/service/MemberWalkServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/walk/service/WalkServiceImpl.java
  src/test/java/com/example/harumeonglog/restDocs/controller/WalkControllerTest.java
Labels: ✨feature

#6 ✨ [Feat] post, notice, comment 관련 api 명세서 추가
  build.gradle
  src/docs/asciidoc/comment.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/notice.adoc
  src/docs/asciidoc/post.adoc
  src/main/java/com/example/harumeonglog/domain/comment/controller/CommentController.java
  src/main/java/com/example/harumeonglog/domain/comment/controller/dto/request/CommentRequest.java
  src/main/java/com/example/harumeonglog/domain/comment/controller/dto/response/CommentResponse.java
  src/main/java/com/example/harumeonglog/domain/comment/controller/port/CommentService.java
  src/main/java/com/example/harumeonglog/domain/comment/domain/Comment.java
  src/main/java/com/example/harumeonglog/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/member/controller/NoticeController.java
  src/main/java/com/example/harumeonglog/domain/member/controller/dto/response/NoticeResponse.java
  src/main/java/com/example/harumeonglog/domain/member/controller/port/NoticeService.java
  src/main/java/com/example/harumeonglog/domain/member/domain/Notice.java
  src/main/java/com/example/harumeonglog/domain/member/service/NoticeServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/post/controller/PostController.java
  src/main/java/com/example/harumeonglog/domain/post/controller/dto/enums/PostCategory.java
  src/main/java/com/example/harumeonglog/domain/post/controller/dto/request/PostRequest.java
  src/main/java/com/example/harumeonglog/domain/post/controller/dto/response/PostResponse.java
  src/main/java/com/example/harumeonglog/domain/post/controller/port/PostService.java
  src/main/java/com/example/harumeonglog/domain/post/domain/Post.java
  src/main/java/com/example/harumeonglog/domain/post/entity/PostEntity.java
  src/main/java/com/example/harumeonglog/domain/post/service/PostServiceImpl.java
  src/test/java/com/example/harumeonglog/restDocs/controller/CommentControllerTest.java
  src/test/java/com/example/harumeonglog/restDocs/controller/NoticeControllerTest.java
  src/test/java/com/example/harumeonglog/restDocs/controller/PostControllerTest.java
Labels: ✨feature

#8 ✨ [Feat] event, pet, petImage관련 api 명세서 추가
  src/docs/asciidoc/event.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/pet.adoc
  src/docs/asciidoc/petImage.adoc
  src/main/java/com/example/harumeonglog/domain/event/controller/EventController.java
  src/main/java/com/example/harumeonglog/domain/event/controller/dto/request/EventRequest.java
  src/main/java/com/example/harumeonglog/domain/event/controller/dto/response/EventResponse.java
  src/main/java/com/example/harumeonglog/domain/event/controller/port/EventService.java
  src/main/java/com/example/harumeonglog/domain/event/domain/Event.java
  src/main/java/com/example/harumeonglog/domain/event/service/EventServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/pet/controller/PetController.java
  src/main/java/com/example/harumeonglog/domain/pet/controller/PetImageController.java
  src/main/java/com/example/harumeonglog/domain/pet/controller/dto/request/PetImageRequest.java
  src/main/java/com/example/harumeonglog/domain/pet/controller/dto/request/PetRequest.java
  src/main/java/com/example/harumeonglog/domain/pet/controller/dto/response/PetImageResponse.java
  src/main/java/com/example/harumeonglog/domain/pet/controller/dto/response/PetResponse.java
  src/main/java/com/example/harumeonglog/domain/pet/controller/port/PetImageService.java
  src/main/java/com/example/harumeonglog/domain/pet/controller/port/PetService.java
  src/main/java/com/example/harumeonglog/domain/pet/service/PetImageServiceImpl.java
  src/main/java/com/example/harumeonglog/domain/pet/service/PetServiceImpl.java
  src/test/java/com/example/harumeonglog/restDocs/controller/EventControllerTest.java
  src/test/java/com/example/harumeonglog/restDocs/controller/PetControllerTest.java
  src/test/java/com/example/harumeonglog/restDocs/controller/PetImageControllerTest.java
Labels: ✨feature

#11 🔨 [Refactor] Pet, PetImage, Event rest docs 리팩토링
  src/docs/asciidoc/event.adoc
  src/docs/asciidoc/pet.adoc
  src/docs/asciidoc/petImage.adoc
  src/main/java/com/example/harumeonglog/domain/event/controller/EventController.java
  src/main/java/com/example/harumeonglog/domain/pet/controller/PetController.java
  src/main/java/com/example/harumeonglog/domain/pet/controller/dto/response/PetResponse.java
  src/main/java/com/example/harumeonglog/domain/pet/controller/port/PetService.java
  src/main/java/com/example/harumeonglog/domain/pet/service/PetServiceImpl.java
  src/test/java/com/example/harumeonglog/restDocs/controller/EventControllerTest.java
  src/test/java/com/example/harumeonglog/restDocs/controller/PetControllerTest.java
  src/test/java/com/example/harumeonglog/restDocs/controller/PetImageControllerTest.java
Labels: refactor

#12 🚀 [Chore] Fix a bug, Refactor, Chore 이슈 템플릿 및 PR 템플릿 추가
  .github/ISSUE_TEMPLATE/chore.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/fix.yml
  .github/ISSUE_TEMPLATE/refactor.yml
  .github/pull_request_template.md
Labels: 🚀chore
